#!/usr/bin/env bash

# curl -X 'POST' 'http://localhost:1323/webhook/trigger_task' -H 'Content-Type: application/json' -d '{
#     "challenge_repo_url": "git@github.com:aixcc-finals/example-libpng.git",
#     "challenge_repo_base_ref": "0cc367aaeaac3f888f255cee5d394968996f736e",
#     "challenge_repo_head_ref": "92407e9d102e36f5538dea21ca87b0dc27817126",
#     "fuzz_tooling_url": "https://github.com/aixcc-finals/oss-fuzz-aixcc.git",
#     "fuzz_tooling_ref": "d5fbd68fca66e6fa4f05899170d24e572b01853d",
#     "fuzz_tooling_project_name": "libpng",
#     "duration": 3600
# }'

curl -X 'POST' 'http://localhost:1323/webhook/trigger_task' -H 'Content-Type: application/json' -d '{
    "challenge_repo_url": "git@github.com:aixcc-finals/example-libpng.git",
    "challenge_repo_base_ref": "0cc367aaeaac3f888f255cee5d394968996f736e",
    "challenge_repo_head_ref": "fdacd5a1dcff42175117d674b0fda9f8a005ae88",
    "fuzz_tooling_url": "https://github.com/aixcc-finals/oss-fuzz-aixcc.git",
    "fuzz_tooling_ref": "d5fbd68fca66e6fa4f05899170d24e572b01853d",
    "fuzz_tooling_project_name": "libpng",
    "duration": 3600
}'