#!/usr/bin/perl
# dupl-template		D. Musliner	$Revision: 1.2 $
# duplicate a template, replacing @ with the duplication count, where duplication counts are bounded by
# DUPL <howmany> and 
# DUPLEND
# - based on CIRCA's duplprims, which replaced #s, but this works on yaml where that's comment char.

## -------------------------------------------------------------------

$/="##DUPLEND\n";	# set record separator
$dupl=1;
$numfbs=shift();

while(<>)
{
  #warn "------------------------record is $_\n";
  s/XXXNUMFBSXXX/$numfbs/;
  if (/^##DUPL\s*:\s*(\d+)/) {
    if ( $numfbs > 0 ) {
      warn "setting dupl to $1\n";
      $dupl = $1;
      s/\/\*\s*DUPL:\s*\d+\s*\*\///;
      $orig = $_;
      
      for ($i=0;$i<$dupl;$i++)
      {
        $offset=3+$i+$ENV{'CIRCA_BASEPORT'};
        warn "fb$i exposing slime with port $offset\n";
        s/XXXSLIMEPORTXXX/$offset/g;
        s/\@/$i/g;
        print;
        $_=$orig;
      }
      $dupl=1;
    }
  }
  else { print; }
  #  if (/^\}/)
  #    {
  #	$dupl=1;
  #	print;
  #    }
}
