#!/usr/bin/env bash

# This accepts a ctask id and a list of Azure SAS urls to download ctask source code

set -e
DEBUG=1

thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd -P "$( dirname "$SOURCE" )" && /bin/pwd )"

PROGNAME=$(basename "$0")
warn()  { echo "$PROGNAME: ${@}" 1>&2; }
die()   { warn "${@}"; exit 1; }
dbug()   { test -z $DEBUG || warn "${@}"; }

export AIXCC_CP_ROOT="${thisdir}/../../../../cp_root"
dbug "AIXCC_CP_ROOT is ${AIXCC_CP_ROOT}"
rm -rf "${AIXCC_CP_ROOT}/*"
${thisdir}/afc-populate-cp-root "$@"
