#!/bin/bash

# test-patch-on-cpvs good_patch.diff

# Check if the required arguments are provided
if [ $# -lt 1 ]; then
    echo "Usage: $0 <patch_name>"
    exit 1
fi

patch_name=$1

subdir_key="patches/good_patch.diff"
# subdir_key="patches/ngx_http_userid_filter_module.c_claude-3.5-sonnet_direct_5v2jj6h1.patch" # cpv15

run-on-subdirs-containing $subdir_key test-lax-ref-patch patches/$patch_name
