#!/bin/bash
# runs inside, eg, OPT0 ctr (unlike normal)
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd -P "$( dirname "$SOURCE" )" && pwd )"
if ! [ -x $thisdir/mm ]; then
   (cd $thisdir/../matchmaker; make all)
fi
if ! [ -x $thisdir/mmhealth ]; then
   (cd $thisdir/../matchmaker; make all)
fi
$thisdir/mmkiller	# try to be nice

# dump list of processes we might kill
pgrep -a mm

echo "Killing old mm"
# -x for exact name so we do not kill mmhealth
# -e to echo what was killed
pkill -x -e -9 -u $USER mm	# then be mean
#sleep 1 &
#wait
$thisdir/../prt/timestamp $thisdir/mm &
