# coding: utf-8

# flake8: noqa
"""
    Example Competition API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.types_architecture import TypesArchitecture
from openapi_client.models.types_assessment import TypesAssessment
from openapi_client.models.types_bundle_submission import TypesBundleSubmission
from openapi_client.models.types_bundle_submission_response import TypesBundleSubmissionResponse
from openapi_client.models.types_bundle_submission_response_verbose import TypesBundleSubmissionResponseVerbose
from openapi_client.models.types_error import TypesError
from openapi_client.models.types_freeform_response import TypesFreeformResponse
from openapi_client.models.types_freeform_submission import TypesFreeformSubmission
from openapi_client.models.types_pov_submission import TypesPOVSubmission
from openapi_client.models.types_pov_submission_response import TypesPOVSubmissionResponse
from openapi_client.models.types_patch_submission import TypesPatchSubmission
from openapi_client.models.types_patch_submission_response import TypesPatchSubmissionResponse
from openapi_client.models.types_ping_response import TypesPingResponse
from openapi_client.models.types_sarif_submission import TypesSARIFSubmission
from openapi_client.models.types_sarif_submission_response import TypesSARIFSubmissionResponse
from openapi_client.models.types_sarif_assessment_response import TypesSarifAssessmentResponse
from openapi_client.models.types_sarif_assessment_submission import TypesSarifAssessmentSubmission
from openapi_client.models.types_submission_status import TypesSubmissionStatus
