from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.types_submission_status import TypesSubmissionStatus
from openapi_server import util

from openapi_server.models.types_submission_status import TypesSubmissionStatus  # noqa: E501

class TypesSARIFSubmissionResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, submitted_sarif_id=None):  # noqa: E501
        """TypesSARIFSubmissionResponse - a model defined in OpenAPI

        :param status: The status of this TypesSARIFSubmissionResponse.  # noqa: E501
        :type status: TypesSubmissionStatus
        :param submitted_sarif_id: The submitted_sarif_id of this TypesSARIFSubmissionResponse.  # noqa: E501
        :type submitted_sarif_id: str
        """
        self.openapi_types = {
            'status': TypesSubmissionStatus,
            'submitted_sarif_id': str
        }

        self.attribute_map = {
            'status': 'status',
            'submitted_sarif_id': 'submitted_sarif_id'
        }

        self._status = status
        self._submitted_sarif_id = submitted_sarif_id

    @classmethod
    def from_dict(cls, dikt) -> 'TypesSARIFSubmissionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The types.SARIFSubmissionResponse of this TypesSARIFSubmissionResponse.  # noqa: E501
        :rtype: TypesSARIFSubmissionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> TypesSubmissionStatus:
        """Gets the status of this TypesSARIFSubmissionResponse.


        :return: The status of this TypesSARIFSubmissionResponse.
        :rtype: TypesSubmissionStatus
        """
        return self._status

    @status.setter
    def status(self, status: TypesSubmissionStatus):
        """Sets the status of this TypesSARIFSubmissionResponse.


        :param status: The status of this TypesSARIFSubmissionResponse.
        :type status: TypesSubmissionStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def submitted_sarif_id(self) -> str:
        """Gets the submitted_sarif_id of this TypesSARIFSubmissionResponse.


        :return: The submitted_sarif_id of this TypesSARIFSubmissionResponse.
        :rtype: str
        """
        return self._submitted_sarif_id

    @submitted_sarif_id.setter
    def submitted_sarif_id(self, submitted_sarif_id: str):
        """Sets the submitted_sarif_id of this TypesSARIFSubmissionResponse.


        :param submitted_sarif_id: The submitted_sarif_id of this TypesSARIFSubmissionResponse.
        :type submitted_sarif_id: str
        """
        if submitted_sarif_id is None:
            raise ValueError("Invalid value for `submitted_sarif_id`, must not be `None`")  # noqa: E501

        self._submitted_sarif_id = submitted_sarif_id
