from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TypesBundleSubmission(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, broadcast_sarif_id=None, description=None, freeform_id=None, patch_id=None, pov_id=None, submitted_sarif_id=None):  # noqa: E501
        """TypesBundleSubmission - a model defined in OpenAPI

        :param broadcast_sarif_id: The broadcast_sarif_id of this TypesBundleSubmission.  # noqa: E501
        :type broadcast_sarif_id: str
        :param description: The description of this TypesBundleSubmission.  # noqa: E501
        :type description: str
        :param freeform_id: The freeform_id of this TypesBundleSubmission.  # noqa: E501
        :type freeform_id: str
        :param patch_id: The patch_id of this TypesBundleSubmission.  # noqa: E501
        :type patch_id: str
        :param pov_id: The pov_id of this TypesBundleSubmission.  # noqa: E501
        :type pov_id: str
        :param submitted_sarif_id: The submitted_sarif_id of this TypesBundleSubmission.  # noqa: E501
        :type submitted_sarif_id: str
        """
        self.openapi_types = {
            'broadcast_sarif_id': str,
            'description': str,
            'freeform_id': str,
            'patch_id': str,
            'pov_id': str,
            'submitted_sarif_id': str
        }

        self.attribute_map = {
            'broadcast_sarif_id': 'broadcast_sarif_id',
            'description': 'description',
            'freeform_id': 'freeform_id',
            'patch_id': 'patch_id',
            'pov_id': 'pov_id',
            'submitted_sarif_id': 'submitted_sarif_id'
        }

        self._broadcast_sarif_id = broadcast_sarif_id
        self._description = description
        self._freeform_id = freeform_id
        self._patch_id = patch_id
        self._pov_id = pov_id
        self._submitted_sarif_id = submitted_sarif_id

    @classmethod
    def from_dict(cls, dikt) -> 'TypesBundleSubmission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The types.BundleSubmission of this TypesBundleSubmission.  # noqa: E501
        :rtype: TypesBundleSubmission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def broadcast_sarif_id(self) -> str:
        """Gets the broadcast_sarif_id of this TypesBundleSubmission.


        :return: The broadcast_sarif_id of this TypesBundleSubmission.
        :rtype: str
        """
        return self._broadcast_sarif_id

    @broadcast_sarif_id.setter
    def broadcast_sarif_id(self, broadcast_sarif_id: str):
        """Sets the broadcast_sarif_id of this TypesBundleSubmission.


        :param broadcast_sarif_id: The broadcast_sarif_id of this TypesBundleSubmission.
        :type broadcast_sarif_id: str
        """

        self._broadcast_sarif_id = broadcast_sarif_id

    @property
    def description(self) -> str:
        """Gets the description of this TypesBundleSubmission.

        optional plaintext description of the components of the bundle, such as would be found in a pull request description or bug report  # noqa: E501

        :return: The description of this TypesBundleSubmission.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TypesBundleSubmission.

        optional plaintext description of the components of the bundle, such as would be found in a pull request description or bug report  # noqa: E501

        :param description: The description of this TypesBundleSubmission.
        :type description: str
        """

        self._description = description

    @property
    def freeform_id(self) -> str:
        """Gets the freeform_id of this TypesBundleSubmission.


        :return: The freeform_id of this TypesBundleSubmission.
        :rtype: str
        """
        return self._freeform_id

    @freeform_id.setter
    def freeform_id(self, freeform_id: str):
        """Sets the freeform_id of this TypesBundleSubmission.


        :param freeform_id: The freeform_id of this TypesBundleSubmission.
        :type freeform_id: str
        """

        self._freeform_id = freeform_id

    @property
    def patch_id(self) -> str:
        """Gets the patch_id of this TypesBundleSubmission.


        :return: The patch_id of this TypesBundleSubmission.
        :rtype: str
        """
        return self._patch_id

    @patch_id.setter
    def patch_id(self, patch_id: str):
        """Sets the patch_id of this TypesBundleSubmission.


        :param patch_id: The patch_id of this TypesBundleSubmission.
        :type patch_id: str
        """

        self._patch_id = patch_id

    @property
    def pov_id(self) -> str:
        """Gets the pov_id of this TypesBundleSubmission.


        :return: The pov_id of this TypesBundleSubmission.
        :rtype: str
        """
        return self._pov_id

    @pov_id.setter
    def pov_id(self, pov_id: str):
        """Sets the pov_id of this TypesBundleSubmission.


        :param pov_id: The pov_id of this TypesBundleSubmission.
        :type pov_id: str
        """

        self._pov_id = pov_id

    @property
    def submitted_sarif_id(self) -> str:
        """Gets the submitted_sarif_id of this TypesBundleSubmission.


        :return: The submitted_sarif_id of this TypesBundleSubmission.
        :rtype: str
        """
        return self._submitted_sarif_id

    @submitted_sarif_id.setter
    def submitted_sarif_id(self, submitted_sarif_id: str):
        """Sets the submitted_sarif_id of this TypesBundleSubmission.


        :param submitted_sarif_id: The submitted_sarif_id of this TypesBundleSubmission.
        :type submitted_sarif_id: str
        """

        self._submitted_sarif_id = submitted_sarif_id
