from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.types_submission_status import TypesSubmissionStatus
from openapi_server import util

from openapi_server.models.types_submission_status import TypesSubmissionStatus  # noqa: E501

class TypesFreeformResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, freeform_id=None, status=None):  # noqa: E501
        """TypesFreeformResponse - a model defined in OpenAPI

        :param freeform_id: The freeform_id of this TypesFreeformResponse.  # noqa: E501
        :type freeform_id: str
        :param status: The status of this TypesFreeformResponse.  # noqa: E501
        :type status: TypesSubmissionStatus
        """
        self.openapi_types = {
            'freeform_id': str,
            'status': TypesSubmissionStatus
        }

        self.attribute_map = {
            'freeform_id': 'freeform_id',
            'status': 'status'
        }

        self._freeform_id = freeform_id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'TypesFreeformResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The types.FreeformResponse of this TypesFreeformResponse.  # noqa: E501
        :rtype: TypesFreeformResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def freeform_id(self) -> str:
        """Gets the freeform_id of this TypesFreeformResponse.


        :return: The freeform_id of this TypesFreeformResponse.
        :rtype: str
        """
        return self._freeform_id

    @freeform_id.setter
    def freeform_id(self, freeform_id: str):
        """Sets the freeform_id of this TypesFreeformResponse.


        :param freeform_id: The freeform_id of this TypesFreeformResponse.
        :type freeform_id: str
        """
        if freeform_id is None:
            raise ValueError("Invalid value for `freeform_id`, must not be `None`")  # noqa: E501

        self._freeform_id = freeform_id

    @property
    def status(self) -> TypesSubmissionStatus:
        """Gets the status of this TypesFreeformResponse.


        :return: The status of this TypesFreeformResponse.
        :rtype: TypesSubmissionStatus
        """
        return self._status

    @status.setter
    def status(self, status: TypesSubmissionStatus):
        """Sets the status of this TypesFreeformResponse.


        :param status: The status of this TypesFreeformResponse.
        :type status: TypesSubmissionStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
