from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TypesSARIFSubmission(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sarif=None):  # noqa: E501
        """TypesSARIFSubmission - a model defined in OpenAPI

        :param sarif: The sarif of this TypesSARIFSubmission.  # noqa: E501
        :type sarif: object
        """
        self.openapi_types = {
            'sarif': object
        }

        self.attribute_map = {
            'sarif': 'sarif'
        }

        self._sarif = sarif

    @classmethod
    def from_dict(cls, dikt) -> 'TypesSARIFSubmission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The types.SARIFSubmission of this TypesSARIFSubmission.  # noqa: E501
        :rtype: TypesSARIFSubmission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sarif(self) -> object:
        """Gets the sarif of this TypesSARIFSubmission.

        SARIF object compliant with the provided schema  # noqa: E501

        :return: The sarif of this TypesSARIFSubmission.
        :rtype: object
        """
        return self._sarif

    @sarif.setter
    def sarif(self, sarif: object):
        """Sets the sarif of this TypesSARIFSubmission.

        SARIF object compliant with the provided schema  # noqa: E501

        :param sarif: The sarif of this TypesSARIFSubmission.
        :type sarif: object
        """
        if sarif is None:
            raise ValueError("Invalid value for `sarif`, must not be `None`")  # noqa: E501

        self._sarif = sarif
