from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.types_submission_status import TypesSubmissionStatus
from openapi_server import util

from openapi_server.models.types_submission_status import TypesSubmissionStatus  # noqa: E501

class TypesSarifAssessmentResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None):  # noqa: E501
        """TypesSarifAssessmentResponse - a model defined in OpenAPI

        :param status: The status of this TypesSarifAssessmentResponse.  # noqa: E501
        :type status: TypesSubmissionStatus
        """
        self.openapi_types = {
            'status': TypesSubmissionStatus
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'TypesSarifAssessmentResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The types.SarifAssessmentResponse of this TypesSarifAssessmentResponse.  # noqa: E501
        :rtype: TypesSarifAssessmentResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> TypesSubmissionStatus:
        """Gets the status of this TypesSarifAssessmentResponse.


        :return: The status of this TypesSarifAssessmentResponse.
        :rtype: TypesSubmissionStatus
        """
        return self._status

    @status.setter
    def status(self, status: TypesSubmissionStatus):
        """Sets the status of this TypesSarifAssessmentResponse.


        :param status: The status of this TypesSarifAssessmentResponse.
        :type status: TypesSubmissionStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
