from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.types_submission_status import TypesSubmissionStatus
from openapi_server import util

from openapi_server.models.types_submission_status import TypesSubmissionStatus  # noqa: E501

class TypesBundleSubmissionResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bundle_id=None, status=None):  # noqa: E501
        """TypesBundleSubmissionResponse - a model defined in OpenAPI

        :param bundle_id: The bundle_id of this TypesBundleSubmissionResponse.  # noqa: E501
        :type bundle_id: str
        :param status: The status of this TypesBundleSubmissionResponse.  # noqa: E501
        :type status: TypesSubmissionStatus
        """
        self.openapi_types = {
            'bundle_id': str,
            'status': TypesSubmissionStatus
        }

        self.attribute_map = {
            'bundle_id': 'bundle_id',
            'status': 'status'
        }

        self._bundle_id = bundle_id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'TypesBundleSubmissionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The types.BundleSubmissionResponse of this TypesBundleSubmissionResponse.  # noqa: E501
        :rtype: TypesBundleSubmissionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bundle_id(self) -> str:
        """Gets the bundle_id of this TypesBundleSubmissionResponse.


        :return: The bundle_id of this TypesBundleSubmissionResponse.
        :rtype: str
        """
        return self._bundle_id

    @bundle_id.setter
    def bundle_id(self, bundle_id: str):
        """Sets the bundle_id of this TypesBundleSubmissionResponse.


        :param bundle_id: The bundle_id of this TypesBundleSubmissionResponse.
        :type bundle_id: str
        """
        if bundle_id is None:
            raise ValueError("Invalid value for `bundle_id`, must not be `None`")  # noqa: E501

        self._bundle_id = bundle_id

    @property
    def status(self) -> TypesSubmissionStatus:
        """Gets the status of this TypesBundleSubmissionResponse.


        :return: The status of this TypesBundleSubmissionResponse.
        :rtype: TypesSubmissionStatus
        """
        return self._status

    @status.setter
    def status(self, status: TypesSubmissionStatus):
        """Sets the status of this TypesBundleSubmissionResponse.


        :param status: The status of this TypesBundleSubmissionResponse.
        :type status: TypesSubmissionStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
