from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.types_submission_status import TypesSubmissionStatus
from openapi_server import util

from openapi_server.models.types_submission_status import TypesSubmissionStatus  # noqa: E501

class TypesBundleSubmissionResponseVerbose(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, broadcast_sarif_id=None, bundle_id=None, description=None, freeform_id=None, patch_id=None, pov_id=None, status=None, submitted_sarif_id=None):  # noqa: E501
        """TypesBundleSubmissionResponseVerbose - a model defined in OpenAPI

        :param broadcast_sarif_id: The broadcast_sarif_id of this TypesBundleSubmissionResponseVerbose.  # noqa: E501
        :type broadcast_sarif_id: str
        :param bundle_id: The bundle_id of this TypesBundleSubmissionResponseVerbose.  # noqa: E501
        :type bundle_id: str
        :param description: The description of this TypesBundleSubmissionResponseVerbose.  # noqa: E501
        :type description: str
        :param freeform_id: The freeform_id of this TypesBundleSubmissionResponseVerbose.  # noqa: E501
        :type freeform_id: str
        :param patch_id: The patch_id of this TypesBundleSubmissionResponseVerbose.  # noqa: E501
        :type patch_id: str
        :param pov_id: The pov_id of this TypesBundleSubmissionResponseVerbose.  # noqa: E501
        :type pov_id: str
        :param status: The status of this TypesBundleSubmissionResponseVerbose.  # noqa: E501
        :type status: TypesSubmissionStatus
        :param submitted_sarif_id: The submitted_sarif_id of this TypesBundleSubmissionResponseVerbose.  # noqa: E501
        :type submitted_sarif_id: str
        """
        self.openapi_types = {
            'broadcast_sarif_id': str,
            'bundle_id': str,
            'description': str,
            'freeform_id': str,
            'patch_id': str,
            'pov_id': str,
            'status': TypesSubmissionStatus,
            'submitted_sarif_id': str
        }

        self.attribute_map = {
            'broadcast_sarif_id': 'broadcast_sarif_id',
            'bundle_id': 'bundle_id',
            'description': 'description',
            'freeform_id': 'freeform_id',
            'patch_id': 'patch_id',
            'pov_id': 'pov_id',
            'status': 'status',
            'submitted_sarif_id': 'submitted_sarif_id'
        }

        self._broadcast_sarif_id = broadcast_sarif_id
        self._bundle_id = bundle_id
        self._description = description
        self._freeform_id = freeform_id
        self._patch_id = patch_id
        self._pov_id = pov_id
        self._status = status
        self._submitted_sarif_id = submitted_sarif_id

    @classmethod
    def from_dict(cls, dikt) -> 'TypesBundleSubmissionResponseVerbose':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The types.BundleSubmissionResponseVerbose of this TypesBundleSubmissionResponseVerbose.  # noqa: E501
        :rtype: TypesBundleSubmissionResponseVerbose
        """
        return util.deserialize_model(dikt, cls)

    @property
    def broadcast_sarif_id(self) -> str:
        """Gets the broadcast_sarif_id of this TypesBundleSubmissionResponseVerbose.


        :return: The broadcast_sarif_id of this TypesBundleSubmissionResponseVerbose.
        :rtype: str
        """
        return self._broadcast_sarif_id

    @broadcast_sarif_id.setter
    def broadcast_sarif_id(self, broadcast_sarif_id: str):
        """Sets the broadcast_sarif_id of this TypesBundleSubmissionResponseVerbose.


        :param broadcast_sarif_id: The broadcast_sarif_id of this TypesBundleSubmissionResponseVerbose.
        :type broadcast_sarif_id: str
        """

        self._broadcast_sarif_id = broadcast_sarif_id

    @property
    def bundle_id(self) -> str:
        """Gets the bundle_id of this TypesBundleSubmissionResponseVerbose.


        :return: The bundle_id of this TypesBundleSubmissionResponseVerbose.
        :rtype: str
        """
        return self._bundle_id

    @bundle_id.setter
    def bundle_id(self, bundle_id: str):
        """Sets the bundle_id of this TypesBundleSubmissionResponseVerbose.


        :param bundle_id: The bundle_id of this TypesBundleSubmissionResponseVerbose.
        :type bundle_id: str
        """
        if bundle_id is None:
            raise ValueError("Invalid value for `bundle_id`, must not be `None`")  # noqa: E501

        self._bundle_id = bundle_id

    @property
    def description(self) -> str:
        """Gets the description of this TypesBundleSubmissionResponseVerbose.


        :return: The description of this TypesBundleSubmissionResponseVerbose.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TypesBundleSubmissionResponseVerbose.


        :param description: The description of this TypesBundleSubmissionResponseVerbose.
        :type description: str
        """

        self._description = description

    @property
    def freeform_id(self) -> str:
        """Gets the freeform_id of this TypesBundleSubmissionResponseVerbose.


        :return: The freeform_id of this TypesBundleSubmissionResponseVerbose.
        :rtype: str
        """
        return self._freeform_id

    @freeform_id.setter
    def freeform_id(self, freeform_id: str):
        """Sets the freeform_id of this TypesBundleSubmissionResponseVerbose.


        :param freeform_id: The freeform_id of this TypesBundleSubmissionResponseVerbose.
        :type freeform_id: str
        """

        self._freeform_id = freeform_id

    @property
    def patch_id(self) -> str:
        """Gets the patch_id of this TypesBundleSubmissionResponseVerbose.


        :return: The patch_id of this TypesBundleSubmissionResponseVerbose.
        :rtype: str
        """
        return self._patch_id

    @patch_id.setter
    def patch_id(self, patch_id: str):
        """Sets the patch_id of this TypesBundleSubmissionResponseVerbose.


        :param patch_id: The patch_id of this TypesBundleSubmissionResponseVerbose.
        :type patch_id: str
        """

        self._patch_id = patch_id

    @property
    def pov_id(self) -> str:
        """Gets the pov_id of this TypesBundleSubmissionResponseVerbose.


        :return: The pov_id of this TypesBundleSubmissionResponseVerbose.
        :rtype: str
        """
        return self._pov_id

    @pov_id.setter
    def pov_id(self, pov_id: str):
        """Sets the pov_id of this TypesBundleSubmissionResponseVerbose.


        :param pov_id: The pov_id of this TypesBundleSubmissionResponseVerbose.
        :type pov_id: str
        """

        self._pov_id = pov_id

    @property
    def status(self) -> TypesSubmissionStatus:
        """Gets the status of this TypesBundleSubmissionResponseVerbose.


        :return: The status of this TypesBundleSubmissionResponseVerbose.
        :rtype: TypesSubmissionStatus
        """
        return self._status

    @status.setter
    def status(self, status: TypesSubmissionStatus):
        """Sets the status of this TypesBundleSubmissionResponseVerbose.


        :param status: The status of this TypesBundleSubmissionResponseVerbose.
        :type status: TypesSubmissionStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def submitted_sarif_id(self) -> str:
        """Gets the submitted_sarif_id of this TypesBundleSubmissionResponseVerbose.


        :return: The submitted_sarif_id of this TypesBundleSubmissionResponseVerbose.
        :rtype: str
        """
        return self._submitted_sarif_id

    @submitted_sarif_id.setter
    def submitted_sarif_id(self, submitted_sarif_id: str):
        """Sets the submitted_sarif_id of this TypesBundleSubmissionResponseVerbose.


        :param submitted_sarif_id: The submitted_sarif_id of this TypesBundleSubmissionResponseVerbose.
        :type submitted_sarif_id: str
        """

        self._submitted_sarif_id = submitted_sarif_id
