from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TypesError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, fields=None, message=None):  # noqa: E501
        """TypesError - a model defined in OpenAPI

        :param fields: The fields of this TypesError.  # noqa: E501
        :type fields: Dict[str, str]
        :param message: The message of this TypesError.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'fields': Dict[str, str],
            'message': str
        }

        self.attribute_map = {
            'fields': 'fields',
            'message': 'message'
        }

        self._fields = fields
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'TypesError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The types.Error of this TypesError.  # noqa: E501
        :rtype: TypesError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fields(self) -> Dict[str, str]:
        """Gets the fields of this TypesError.


        :return: The fields of this TypesError.
        :rtype: Dict[str, str]
        """
        return self._fields

    @fields.setter
    def fields(self, fields: Dict[str, str]):
        """Sets the fields of this TypesError.


        :param fields: The fields of this TypesError.
        :type fields: Dict[str, str]
        """

        self._fields = fields

    @property
    def message(self) -> str:
        """Gets the message of this TypesError.


        :return: The message of this TypesError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this TypesError.


        :param message: The message of this TypesError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
